---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "whisper-app"
  namespace: "default"
  labels:
    app: "whisper-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "whisper-app"
  template:
    metadata:
      labels:
        app: "whisper-app"
    spec:
      containers:
      - name: "whisper-app-sha256-1"
        image: "gcr.io/polyglot-417619/whisper.app@sha256:570c6f0bbd62985e253f863284d6ffb7866614c78eadfbfca9107eaff4b6e4c3"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "whisper-app-hpa-oa71"
  namespace: "default"
  labels:
    app: "whisper-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "whisper-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
